# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-29 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, null=True)),
                ('schedule', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
